<?php

require_once __DIR__ . '/../../src/Models/Event.php';
require_once __DIR__ . '/../../src/Models/CompetitionSession.php';
require_once __DIR__ . '/../../src/Models/ScoreEntry.php';

/**
 * Development seed data.
 *
 * Everything below is clearly fake/placeholder content for local testing --
 * NOT the real Sci-Math Battle content, and not meant to ship to production.
 * Image paths point at placeholder filenames; no actual image files are
 * generated by this seeder (see README "Local development" for how to swap
 * in real uploads once the admin upload UI exists).
 */
class DevSeeder
{
    public static function run(): void
    {
        echo "Seeding sample event...\n";

        $event = Event::create([
            'name'             => '2026 Sample Sci-Math Battle (SEED DATA)',
            'subtitle'         => 'Demo event for local development -- not real content',
            'event_date'       => date('Y-m-d', strtotime('+14 days')),
            'status'           => EventStatus::READY,
        ]);
        $eventId = (int) $event['id'];
        echo "  event #{$eventId} created\n";

        $settings = EventSetting::createDefaultsFor($eventId);
        EventSetting::update($settings['id'], [
            'default_points'       => 10,
            'default_time_seconds' => 60,
        ]);
        echo "  event_settings created\n";

        CompetitionSession::createFor($eventId);
        echo "  competition_session created\n";

        // --- Categories -----------------------------------------------
        $categoryNames = ['Mathematics', 'Physics', 'Chemistry', 'Biology'];
        $categories = [];
        foreach ($categoryNames as $i => $name) {
            $categories[$name] = Category::create([
                'event_id'      => $eventId,
                'name'          => $name,
                'description'   => "Sample {$name} category (seed data)",
                'display_order' => $i,
            ]);
        }
        echo "  " . count($categories) . " categories created\n";

        // --- Contestants -------------------------------------------------
        $contestantDefs = [
            ['name' => 'Team Alpha',  'team_code' => 'A', 'organization' => 'Sample High School'],
            ['name' => 'Team Bravo',  'team_code' => 'B', 'organization' => 'Sample Science Academy'],
            ['name' => 'Team Charlie', 'team_code' => 'C', 'organization' => 'Sample STEM Institute'],
        ];
        $contestants = [];
        foreach ($contestantDefs as $i => $def) {
            $contestants[] = Contestant::create([
                'event_id'       => $eventId,
                'name'           => $def['name'],
                'team_code'      => $def['team_code'],
                'organization'   => $def['organization'],
                'starting_score' => 0,
                'display_order'  => $i,
            ]);
        }
        echo "  " . count($contestants) . " contestants created\n";

        // --- Questions ---------------------------------------------------
        // Mix of default timing/points and per-question overrides, matching
        // the example in the spec (Q3/Q4 get longer time limits).
        $questionDefs = [
            ['category' => 'Mathematics', 'points' => null, 'time' => null],
            ['category' => 'Physics',     'points' => null, 'time' => null],
            ['category' => 'Chemistry',   'points' => 15,   'time' => 90],
            ['category' => 'Biology',     'points' => 20,   'time' => 120],
            ['category' => 'Mathematics', 'points' => null, 'time' => null],
        ];
        $questions = [];
        foreach ($questionDefs as $i => $def) {
            $questions[] = Question::create([
                'event_id'        => $eventId,
                'category_id'     => $categories[$def['category']]['id'],
                'question_number' => $i + 1,
                'image_path'      => "uploads/questions/seed-placeholder-q" . ($i + 1) . ".png",
                'points'          => $def['points'],
                'time_seconds'    => $def['time'],
                'display_order'   => $i,
            ]);
        }
        echo "  " . count($questions) . " questions created\n";

        // --- Sample scoring history for question 1 (demonstrates the
        // score_entries + score_adjustments audit trail working end-to-end,
        // including one correction) ---------------------------------------
        $q1 = $questions[0];
        $settingsRow = EventSetting::forEvent($eventId);

        ScoreEntry::recordResult(
            $eventId,
            (int) $q1['id'],
            (int) $contestants[0]['id'],
            AnswerResult::CORRECT,
            Question::effectivePoints($q1, $settingsRow),
            'seed-operator'
        );
        ScoreEntry::recordResult(
            $eventId,
            (int) $q1['id'],
            (int) $contestants[1]['id'],
            AnswerResult::INCORRECT,
            0,
            'seed-operator'
        );
        // Team Charlie initially marked "no answer", then corrected to
        // "correct" after judges review -- demonstrates the audit trail.
        ScoreEntry::recordResult(
            $eventId,
            (int) $q1['id'],
            (int) $contestants[2]['id'],
            AnswerResult::NO_ANSWER,
            0,
            'seed-operator'
        );
        ScoreEntry::recordResult(
            $eventId,
            (int) $q1['id'],
            (int) $contestants[2]['id'],
            AnswerResult::CORRECT,
            Question::effectivePoints($q1, $settingsRow),
            'seed-operator',
            'Judges review: answer was correct, missed on first pass'
        );
        echo "  sample score_entries + one correction (score_adjustments) created\n";

        echo "Done. Sample event id = {$eventId}\n";
    }
}
